language: ruby
rvm:
  - 2.3.0

addons:
  postgresql: '9.5'
env:
  - DB=sqlite
  - DB=postgresql
script:
  - postgres --version
  - env COLUMNS=132 dpkg -l | grep postgres
  - dpkg-query -L postgresql-9.5
  - dpkg-query -L postgresql-client-9.5
  - dpkg-query -L postgresql-contrib-9.5
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database ena_test' -U postgres
