language: ruby
rvm:
  - 2.2.0
before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo cp /etc/postgresql/9.3/main/pg_hba.conf ./
  - sudo apt-get update
  - sudo apt-get purge postgresql-9.1 postgresql-9.2 postgresql-9.3
  - sudo apt-get install libicu-dev cmake language-pack-es postgresql-9.4
  - sudo cp ./pg_hba.conf /etc/postgresql/9.4/main
  - sudo /etc/init.d/postgresql start
env:
  - DB=sqlite
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database ena_test' -U postgres
