language: ruby
rvm:
  - 2.2.0
before_install:
  - sudo apt-get update && sudo apt-get install libicu-dev cmake postgresql-9.4
env:
  - DB=sqlite
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database ena_test' -U postgres
